[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["node node_modules/expo/bin/cli export --platform web --output-dir dist"]

[start]
cmd = "node server.js"
